# Generated by Django 5.2.4 on 2025-07-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tikets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date',
        ),
    ]
